apiVersion: batch/v1
kind: Job
metadata:
  name: link-image-pull-secret
spec:
  template:
    spec:
      serviceAccountName: ${{ values.app_name }}-sa
      containers:
        - name: link-secret
          image: quay.io/openshift/origin-cli:latest # OpenShift CLIイメージを使用
          command: ["/bin/bash", "-c"]
          args:
            - >
              oc secrets link ${{ values.app_name }}-sa quay-credentials --for=pull &&
              echo "Secret linked successfully."
      restartPolicy: Never
  backoffLimit: 3
