apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  links:
  - url: https://openshift-gitops-server-openshift-gitops.${{ values.cluster_url }}/applications/openshift-gitops/${{ values.app_name }}-dev
    title: ArgoCD
    icon: dashboard
  - url: https://${{ values.app_name }}-${{ values.app_name }}-develop.${{ values.cluster_url }}
    title: Application
    icon: dashboard
  - url: https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.app_name }}-app
    title: App Repository
    icon: dashboard
  - url: https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.app_name }}-manifest
    title: Manifest Repository
  - url: https://devspaces.${{ values.cluster_url }}/#https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.app_name }}-app
    title: OpenShift Dev Spaces (VS Code)
    icon: web
  - url: https://console-openshift-console.${{ values.cluster_url }}/k8s/ns/${{ values.app_name }}-develop/tekton.dev~v1~Pipeline/${{ values.app_name }}-pipeline
    title: Tekton Pipelines
    icon: dashboard
  annotations:
    {%- if values.ci_tool == 'tekton' %}
    janus-idp.io/tekton : ${{ values.app_name }}
    janus-idp.io/tekton-enabled : 'true'
    {%- endif %}
    {%- if values.git == 'github' %}
    github.com/project-slug: ${{ values.git_owner_name }}/${{ values.app_name }}-app
    {%- endif %}
    {%- if values.git == 'gitlab' %}
    gitlab.com/project-slug: ${{ values.git_owner_name }}/${{ values.app_name }}-app
    {%- endif %}
    {%- if values.registry == 'quay' %}
    quay.io/repository-slug: skitamura-quay-org/${{ values.app_name }}-develop/${{ values.app_name }}
    {%- endif %}
    argocd/app-selector: argocd.argoproj.io/instance=${{ values.app_name }}-bootstrap
    tektonci/build-namespace: ${{ values.app_name }}-develop
    backstage.io/kubernetes-id: ${{ values.app_name }}
    backstage.io/kubernetes-namespace: ${{ values.app_name }}-develop
    #backstage.io/techdocs-ref: url:https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.app_name }}-app
    backstage.io/techdocs-ref: url:https://github.com/rhdh-skitamura-org/rhdh-nodejs-goldenpath
    #circleci.com/project-slug: ${{ values.git }}/${{ values.git_owner_name }}/${{ values.app_name }}-app
    sonarqube.org/project-key: ${{ values.app_name }}
    jira/project-key: KAN
    sysdigcloud.com/kubernetes-namespace-name: ${{ values.app_name }}-develop
    sysdigcloud.com/kubernetes-workload-type: deployment
    sysdigcloud.com/kubernetes-workload-name: ${{ values.app_name }} 
    sysdigcloud.com/kubernetes-cluster-name: rosa-hcp-1544
    sysdigcloud.com/registry-name: ${{ values.registry_url }}
    sysdigcloud.com/registry-repository: skitamura-quay-org/${{ values.app_name }}-develop/${{ values.app_name }}
    #sysdigcloud.com/kubernetes-distribution: OCP4
    sysdigcloud.com/resource-name: ${{ values.app_name }}
    sysdigcloud.com/resource-type: "Deployment"
    sysdigcloud.com/image-freetext: ${{ values.registry_url }}/skitamura-quay-org/${{ values.app_name }}-develop/${{ values.app_name }}
    #sysdigcloud.com/kubernetes-node-type: Worker
spec:
  type: api 
  system: ${{ values.system | dump }}
  lifecycle: production
  owner: ${{ values.owner | dump }}
  git: ${{ values.git }}
  git_host_url: ${{ values.git_host_url }}
  git_owner_name: ${{ values.git_owner_name }}
