apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  links:
  - url: https://openshift-gitops-server-openshift-gitops.${{ values.cluster_url }}/applications/openshift-gitops/${{ values.app_name }}-dev
    title: ArgoCD
    icon: dashboard
  - url: https://${{ values.app_name }}-${{ values.app_name }}-develop.${{ values.cluster_url }}
    title: Application
    icon: dashboard
  - url: https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.app_name }}-app
    title: App Repository
    icon: dashboard
  - url: https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.app_name }}-manifest
    title: Manifest Repository
  - url: https://devspaces.${{ values.cluster_url }}/#https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.app_name }}-app
    title: OpenShift Dev Spaces (VS Code)
    icon: web
  - url: https://console-openshift-console.${{ values.cluster_url }}/k8s/ns/${{ values.app_name }}-develop/tekton.dev~v1~Pipeline/${{ values.app_name }}-pipeline
    title: Tekton Pipelines
    icon: dashboard
  annotations:
    argocd/app-selector: argocd.argoproj.io/instance=${{ values.app_name }}-bootstrap
    tektonci/build-namespace: ${{ values.app_name }}-develop
    backstage.io/kubernetes-id: ${{ values.app_name }}
    backstage.io/kubernetes-namespace: ${{ values.app_name }}-develop
    janus-idp.io/tekton-enabled : 'true'
    janus-idp.io/tekton : ${{ values.app_name }}
    backstage.io/techdocs-ref: url:https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.app_name }}-app
    github.com/project-slug: ${{ values.git_owner_name }}/${{ values.app_name }}-app
    #circleci.com/project-slug: ${{ values.git }}/${{ values.git_owner_name }}/${{ values.app_name }}-app
    sonarqube.org/project-key: ${{ values.app_name }}
    jira/project-key: KAN
    quay.io/repository-slug: skitamura-quay-org/${{ values.app_name }}-develop/${{ values.app_name }}-record
spec:
  type: api 
  system: ${{ values.system | dump }}
  lifecycle: production
  owner: ${{ values.owner | dump }}
  git: ${{ values.git }}
  git_host_url: ${{ values.git_host_url }}
  git_owner_name: ${{ values.git_owner_name }}
